# Generated by Django 2.2.1 on 2019-05-28 19:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_article_is_visible'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auteur', models.CharField(max_length=42)),
                ('email', models.EmailField(max_length=254)),
                ('contenu', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Commentaire visible ?')),
            ],
            options={
                'verbose_name': 'commentaire',
                'ordering': ['date'],
            },
        ),
    ]
