# Generated by Django 2.2.1 on 2019-05-28 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_commentaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='article_lie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Article'),
        ),
    ]
