# Generated by Django 2.2.1 on 2019-05-29 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_commentaire_article_lie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentaire',
            old_name='article_lie',
            new_name='article',
        ),
    ]
