# Generated by Django 2.2.1 on 2019-05-29 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190529_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentaire',
            old_name='auteur',
            new_name='pseudo',
        ),
    ]
