# Generated by Django 2.2.1 on 2019-06-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_eleve'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='classe',
            field=models.CharField(default='1ère', max_length=31),
        ),
        migrations.AddField(
            model_name='eleve',
            name='sexe',
            field=models.CharField(default='F', max_length=1),
        ),
    ]
