# Generated by Django 2.2.1 on 2019-05-27 16:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiniURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('URLField', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('pseudo', models.CharField(max_length=20, null=True)),
                ('nb_acces', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Raccourci',
            },
        ),
    ]
