# Generated by Django 2.2.1 on 2019-05-27 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_url', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MiniURL',
            new_name='Raccourci',
        ),
    ]
