# Generated by Django 2.2.1 on 2019-05-28 11:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mini_url', '0002_auto_20190527_1837'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='raccourci',
            options={'verbose_name': 'Mini URL'},
        ),
        migrations.AlterField(
            model_name='raccourci',
            name='URLField',
            field=models.CharField(max_length=100, unique=True, verbose_name='URL à réduire'),
        ),
        migrations.AlterField(
            model_name='raccourci',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'enregistrement"),
        ),
        migrations.AlterField(
            model_name='raccourci',
            name='nb_acces',
            field=models.IntegerField(default=0, verbose_name="Nombre d'accès à l'URL"),
        ),
        migrations.AlterField(
            model_name='raccourci',
            name='pseudo',
            field=models.CharField(max_length=20, null=True, verbose_name='Pseudo'),
        ),
    ]
