# Generated by Django 2.2.1 on 2019-06-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_url', '0003_auto_20190528_1130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='raccourci',
            options={'verbose_name': 'Mini URL', 'verbose_name_plural': 'Minis URL'},
        ),
        migrations.AlterField(
            model_name='raccourci',
            name='URLField',
            field=models.URLField(unique=True, verbose_name='URL à réduire'),
        ),
        migrations.AlterField(
            model_name='raccourci',
            name='code',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
